# .github/workflows/ci-cd.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm' # Cache for npm

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Format Check
        run: npm run format:check

      - name: Type Check
        run: npm run type-check

      - name: Run Tests
        run: npm test

      - name: Build Application # Ensure build functions
        run: npm run build